### ISSUE TITLE
Any bans reported yet?

### ISSUE THREAD

**Issue by piyushpaliwal** [veger/foei#20]
Hi, this definitely looks promising, however since I have already got multiple bans on my account for trying out various other helper solutions, am a little hesitant on using it.

Want to understand if you have got any reports of people getting banned because of this yet? It would be also good to know if you are personally using it on your main account successfully?

**Comment by veger** [comment]
Hey,

I have never heard of any bans due to FoEI. And I know of several people (including me) on first hand they are using the tool for a long time already.

As stated in the [README](https://github.com/veger/foei/blob/master/README.md)

> ## Safe
>
> I believe FoEI is safe enough to be (virtually) undetectable by the game servers.
> Mostly, because FoEI does not send _anything_ to the game servers, it only listens to the incoming traffic.
> Thus making it (nearly) impossible to detect!
> 
> Only two possibilities I see how it can detected are:
> 
> * Game code gets changed to detect the 'listening code' that FoEI inserts into the native Javascript (it is not messing with the game code itself!).
  This would be possible but pretty hard, and probably not so robust to implement into the game while supporting different browsers and platforms.
> * Game tracks player behaviour and notices changes (behaviour becomes more efficient that before).
  This could be mitigated by the player by not changing behaviour too fast but more gradually over time.

This still holds. So the risk is minimal (as the tool does not send any traffic), there is some way for them to find out. But AFAIK this has not happened.
