### ISSUE TITLE
Should this be a public project?

### ISSUE THREAD

**Issue by kronikpillow** [veger/foei#21]
Seems plunder info has been removed from JSON (or my tool is bugged), also GB last donation was removed from JSON data of FOE ... I believe this project is the reason behind it, you should consider making this a more closed project and not so public before Inno creates a way to detect things like this, as I am pretty sure Inno is aware of this project, and they are removing any data that can be used to gain advantage ... we had something similar, but we kept it to a closed circle of people and top secret, then we found this, and Inno stopped dropping features

**Comment by veger** [comment]
As of today, plunder info is still there (I just checked and I see it in FoEI on the Plunder tab), so I think your tool is bugged?

The GB last donation is indeed removed, but Inno was not using this data itself at all... So I think they clean up some left over code/data to reduce their bandwidth/network usage.

As long as this tool only _reads_ the FoE data, I don't believe Inno cares much about it. Since anyone can read the data in their browsers (and Inno knows it: take a look at the `x-joinus` header in each HTTP response :stuck_out_tongue: )
So I doubt that Inno is removing info just because there is a handful of people using this tool (AFAIK it is not widely in use). If this tool is the reason, I feel honored and they should give me a job... :wink:
